# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='sold_date',
            field=models.DateTimeField(null=True),
        ),
    ]
