# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0002_auto_20160812_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='gcd_id',
        ),
    ]
