# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0003_remove_issue_gcd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='gcd_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
