# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0004_issue_gcd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='issue_ct',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
