# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0007_auto_20160823_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='genre_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comix.Genre'),
        ),
    ]
