# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0008_auto_20160823_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='catalog_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='gcd_series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comix.Series', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='genre_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comix.Genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='number',
            field=models.IntegerField(verbose_name='Issue No.'),
        ),
    ]
