# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0009_auto_20160828_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='comix.Tag'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
