# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0010_auto_20160924_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, to='comix.Tag'),
        ),
    ]
