# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0011_auto_20160926_0229'),
    ]

    operations = [
    #     migrations.RenameField(
    #         model_name='issue',
    #         old_name='gcd_series_id',
    #         new_name='gcd_series',
    #     ),
    #     migrations.RenameField(
    #         model_name='issue',
    #         old_name='genre_id',
    #         new_name='genre',
    #     ),
    #     migrations.RenameField(
    #         model_name='series',
    #         old_name='gcd_publisher_id',
    #         new_name='gcd_publisher',
    #     ),
    #     migrations.RemoveField(
    #         model_name='series',
    #         name='id',
    #     ),
    #     migrations.AlterField(
    #         model_name='series',
    #         name='gcd_id',
    #         field=models.IntegerField(primary_key=True, serialize=False),
    #     ),
    ]
