# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0012_auto_20161001_1514'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='issue',
        #     old_name='gcd_series_id',
        #     new_name='gcd_series',
        # ),
        # migrations.RenameField(
        #     model_name='issue',
        #     old_name='genre_id',
        #     new_name='genre',
        # ),
        # migrations.RenameField(
        #     model_name='series',
        #     old_name='gcd_publisher_id',
        #     new_name='gcd_publisher',
        # ),
    ]
