# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0014_auto_20161001_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
