# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0015_auto_20161002_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='gcd_notes',
            field=models.TextField(blank=True),
        ),
    ]
