# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0017_issue_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='show_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
