# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0018_issue_show_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='hrn_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='notes_preview',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='numerical_grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
            preserve_default=False,
        ),
    ]
