# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0020_auto_20170126_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='si',
        ),
    ]
