# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0021_remove_issue_si'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='notes_preview',
        ),
        migrations.AlterField(
            model_name='issue',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
