# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0023_issue_publisher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
