# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-02 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0024_pubcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubcount',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
