# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0025_pubcount_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tim_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='tim_year',
            field=models.IntegerField(default=0),
        ),
    ]
