# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0026_auto_20170221_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='gcd_notes',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='variants',
        ),
    ]
