# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0027_auto_20180123_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_scanned', models.BooleanField()),
                ('file_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comix.Image'),
        ),
    ]
