# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0028_auto_20180126_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='images',
        ),
        migrations.AddField(
            model_name='issue',
            name='images',
            field=models.ManyToManyField(null=True, to='comix.Image'),
        ),
    ]
