# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0029_auto_20180126_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
