# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0031_auto_20180126_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='cover_image',
        ),
    ]
