# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0032_remove_issue_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sort_title',
            field=models.CharField(default='not-yet-titled', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='Not yet titled', max_length=255),
        ),
    ]
