# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0034_auto_20180130_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='gcd_series_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
