# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0035_issue_gcd_series_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='tim_year',
            new_name='year_begun',
        ),
    ]
