# Generated by Django 2.0.2 on 2018-02-03 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comix', '0036_auto_20180202_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comix.Genre', verbose_name='Genre'),
        ),
    ]
