# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='username',
            new_name='user',
        ),
    ]
