# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20161114_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
    ]
